### PR TITLE
Remove accepts dependency

### PR DESCRIPTION
**Pull request by benmccann**
I wasn't able to test this locally because of the use of git submodules. I was getting the error:
```
fatal: remote error: upload-pack: not our ref 677b3a7d4bb0c541ce5b0e4e178093f73d89a20e
fatal: Fetched in submodule path 'middlewares/hyper-express-body-parser', but it did not contain 677b3a7d4bb0c541ce5b0e4e178093f73d89a20e. Direct fetching of that commit failed.
```

I think this should work or close to it though

It looks like this project doesn't have a CI? It'd be great to setup GitHub Actions

### CODE REVIEW

**Comment by kartikk221** [comment]
Hello, I originally used `accepts` dependency to match the expected behavior of Express.js as it also uses this dependency under the hood.

What are you reasons for switching from `accepts` to `negotiator` and what would be pros / cons?

**Comment by benmccann** [comment]
Oh, sorry for providing no details in the PR description. I'm not sure what I was thinking.

The reason I did this is to work on reducing the number of dependencies this project requires. This maintains the same logic because `accepts` utilizes `negotiator` under the covers, but it removes `accepts` and its dependencies as an unnecessary wrapper.
https://npmgraph.js.org/?q=accepts

**Comment by kartikk221** [comment]
While this is certainly a good goal to work towards, could you just do some brief research within the `accepts` codebase and ensure that by cutting away `accepts` and depending directly on negotiator, we aren't sacrificing any additional logic / safeties which may make this a breaking change?

**Comment by benmccann** [comment]
I looked at every call we're making to the `accepts` library while putting this PR together. It should all be equivalent. I would be too scared to change any functionality :laughing:

**Comment by kartikk221** [comment]
Seems that your package.json / package-lock.json are conflicting with negotiator.

**Comment by benmccann** [comment]
addressed the merge conflict

**Comment by ratchetsniper2** [comment]
Why the accepts() function still use the accepts dependencies?
It should use mediaTypes from negotiator.

And the flattened function only works with arguments list.
But accepts* functions should works with array or arguments list.

Please remove flattened function and update all accepts* functions with this template:

accepts() {
    if (arguments.length === 0) {
        return this.#negotiator.mediaTypes();
    } else if (Array.isArray(arguments[0])) {
        return this.#negotiator.mediaType(arguments[0]);
    }
    return this.#negotiator.mediaType(...arguments);
}

I can't do pull request, i let you do it.

**Pull request merged**
