### PR TITLE
Add asWritable to get a stream.Writable representation of Response

### PR DESCRIPTION
**Pull request by snowbldr**
I need to be able to stream the response to the caller. 

I tried making Response extend Writable, but chose to make an asWritable function because there's already a write function on Response. Implementing Writable would mean changing the semantics of write, which is probably not desirable.

Additionally, I needed to be able to send headers before writing the response, so I made a method for explicitly sending the headers. I was not able to re-use the completed boolean for the header state because it make it impossible to call end after sending the headers. 

Additionally, I added getHeaderNames to allow iteration of headers because currently there's not way to do that as the headers field is private. 

I also added hyper-express-session to the tests dependencies since it's required to run.

### CODE REVIEW

**Comment by kartikk221** [comment]
So there's a few problems I see with this pull request:

- Any newly implemented methods/properties should follow underscore casing for consistency. The only methods that are implemented in camel case are compatibility methods from ExpressJS.

- Instead of implementing a method which allows the user to manually send headers. The write() method is actually incorrectly implemented as uWebsockets.js will write 200 status code as soon as any response data is sent meaning the final send() call to end the response will be unable to write proper status code. I'll be pushing a bug fix for the write() method so it will write status code and headers on the first write() call.

- A getHeaderNames() method would be redundant as there are various ExpressJS compatibility methods implemented which allow you to read/iterate over queued headers for a Response.

- hyper-express-session is a git submodule in the middlewares/hyper-express-session path in the repository. You should be able to init and sync the submodule and then run "npm install" in the root and tests directories to be able to run all tests. Since hyper-express-session is not neccessary for hyper-express to operate it should not be placed in the package.json file.

In the upcoming 5.1.0 update, I will be implementing a way to easily pipe read streams to a response. For now, the bug fix to the write() method should fix your problems as its behavior should now be to write status code/header on first invocation.

**Comment by kartikk221** [comment]
Response streaming has been added in 5.1.0 through the Response.stream() method.
See documentation for the Response component.

**Comment by snowbldr** [comment]
Can you please update the documentation with information about which methods are available to iterate the headers? Linking to express's github repo in the response docs isn't helpful. At the very least it should link to the relevant documentation and not their repository...

Something like what https://www.npmjs.com/package/uwebsockets-express does would be ideal. Unless you're saying that ALL methods from express are implemented, in which case an explicit comment stating that all functionality is implemented would be helpful. 

I can't use your streaming implementation because I don't know the size of the response body, the response body is too big to fit in memory, and having to load the entire body into memory to check it's length defeats the point of streaming it to begin with. This implementation does not have that problem. I opened an issue.

I added hyper-express-session to the _tests_ package.json, and did not add it as a dependency to hyper-express. hyper-express-session _is_ necessary for hyper-express tests to operate. If you don't want to add it there, you should add documentation about how to run the tests with instructions about checking out the submodule.

**Comment by kartikk221** [comment]
- All methods from the current ExpressJS documentation and older non documented deprecated methods from ExpressJS for both the Request/Response component have been implemented. This is essentially what allows for high compatibility with both newer and older ExpressJS middlewares. You can use either the ExpressJS docs, JSDoc intellisense in VS Code or looking at the Response component to see all of the available redundant methods for iterating or retrieving the private headers object.

- Will look into creating a doc page for which methods have been implemented and which have not. Also, I have also implemented unsupported methods/properties that will throw a descriptive error when invocated to let you know one of your middlewares/logic is trying to invocate an unsupported ExpressJS method.

- See your issue for a response regarding this matter.

- Will add instructions for executing tests in the next update as well.

**Pull request closed without merging**
