### PR TITLE
Streams fix

### PR DESCRIPTION
**Pull request by piliugin-anton**

### CODE REVIEW

**Comment by piliugin-anton** [comment]
I removed write_offset getter, because I don't understand what will be the result of slice with offset + 1, could you explain, what it does?

**Comment by kartikk221** [comment]
So the `write_offset` getter was there to act as an abstraction on top of the `getWriteOffset()` method of uWS. I'm not sure what you mean by offset + 1 but If you asking why it returns -1 when completed, that is just to prevent discarded access errors.

**Comment by piliugin-anton** [comment]
I think I solved this issue by adding if condition that checks for completion, I haven't tested this code btw

**Comment by piliugin-anton** [comment]
Okay, I'm watching your repo, will update my package if you will find a bugs

**Pull request merged**
