### PR TITLE
Fix some request fields types and handle async errors

### PR DESCRIPTION
**Pull request by vpalmisano**

### CODE REVIEW

**Comment by kartikk221** [comment]
Hey the type corrections look good but I was wondering why you modified lines 451 and 464 to pass the next callback twice in the then handler? Any async errors thrown in the middleware will be picked up by the global error handler. If I'm not mistaken passing a callback twice to a then parameter won't change anything in the execution. See below for a snippet of this:
```js
function next(){
    console.log('next called');
}

const promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve(), 0);
});

promise.then(next, next);
```

**Comment by vpalmisano** [comment]
If you add more than 1 async middlewares, and the 2nd throws an exception, that error will not be caught by the global try catch, making the entire process crashing. I thought that it is not catching the error because you are calling the handlers using a recursive function call.

**Comment by kartikk221** [comment]
In that case, we would have to add a .catch which then invokes the response.throw_error(error) call to trigger the global error handler. I don't think passing next twice into the then handler will solve this problem.

**Comment by vpalmisano** [comment]
> In that case, we would have to add a .catch which then invokes the response.throw_error(error) call to trigger the global error handler. I don't think passing next twice into the then handler will solve this problem.

The second next() handler will be called with the thrown error instance, so at the next recursive call it will reach `if (error instanceof Error) return response.throw_error(error);`

**Comment by kartikk221** [comment]
Ohh I see, that is really odd behavior by the Promise.then() method. I never knew you could pass two handlers to the Promise.then() with the second parameter being the catch callback. With that said though, I think it would be much more maintainable/readable if the output Promises had .catch() assignments instead of two next handlers in the then() since I don't think this is commonly known behavior for Promises.

**Pull request merged**
