### PR TITLE
remove cookie-signature dependency

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by kartikk221** [comment]
Hello, your change replaces the `cookie-signature` dependency which currently matches the usage within Express core with an opinionated signature generation snippet. I am not sure If we can chalk this change to be non-breaking with a guarantee.

Do you have any specific reasoning for this change? What are the pros / cons?

**Comment by benmccann** [comment]
This is an equivalent implementation as I basically just copied the implementation. I didn't think it was worth a while extra dependency for what is a 1-liner

**Comment by kartikk221** [comment]
Could you also ensure that you migrate away from `cookie-signature` within the `Request` class as well which supports the `unsign` method by depending on `cookie-signature`.

**Comment by benmccann** [comment]
oh, thanks for catching that. not sure how I missed it. this is more complicated then and may not be worth it

**Pull request closed without merging**
